### ISSUE TITLE
Hard Light Blade becomes Hard Light Club after deactivation

### ISSUE THREAD

**Issue by DrPariah** [yay855/ChorusMod#2]
Found this out the hard way. Crafted a hard light blade, turned it on, and upon turning it off discovered that I had a hard light club instead.

FIX: just needs to have the item revert back to hard light blade (off) when you turn it off, rather than hard light club.

**Comment by yay855** [comment]
This is now fixed, the hard light blade should deactivate into its own deactivated form, rather than the hard light club.
